"""Initial schema v3.2.4

Revision ID: 001
Revises: 
Create Date: 2026-03-02 13:44:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create user table
    op.create_table(
        'user',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('avatar', sa.String(), nullable=True),
        sa.Column('plan', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('verification_code', sa.String(), nullable=True),
        sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True),
        sa.Column('auth_provider', sa.String(), nullable=True),
        sa.Column('provider_id', sa.String(), nullable=True),
        sa.Column('access_token', sa.String(), nullable=True),
        sa.Column('refresh_token', sa.String(), nullable=True),
        sa.Column('token_expires_at', sa.DateTime(), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.create_index(op.f('ix_user_provider_id'), 'user', ['provider_id'], unique=False)
    
    # Create thread table
    op.create_table(
        'thread',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('agent_type', sa.String(), nullable=False),
        sa.Column('agent_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('task_session_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('thread_mode', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_agent_id'), 'thread', ['agent_id'], unique=False)
    op.create_index(op.f('ix_thread_agent_type'), 'thread', ['agent_type'], unique=False)
    op.create_index(op.f('ix_thread_status'), 'thread', ['status'], unique=False)
    op.create_index(op.f('ix_thread_task_session_id'), 'thread', ['task_session_id'], unique=False)
    op.create_index(op.f('ix_thread_thread_mode'), 'thread', ['thread_mode'], unique=False)
    op.create_index(op.f('ix_thread_user_id'), 'thread', ['user_id'], unique=False)
    
    # Create message table
    op.create_table(
        'message',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('thread_id', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_thread_id'), 'message', ['thread_id'], unique=False)
    op.create_index('idx_message_thread_timestamp', 'message', ['thread_id', 'timestamp'], unique=False)
    
    # Create custom_agent table
    op.create_table(
        'customagent',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('system_prompt', sa.String(), nullable=False),
        sa.Column('model_id', sa.String(), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('conversation_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customagent_is_default'), 'customagent', ['is_default'], unique=False)
    op.create_index(op.f('ix_customagent_name'), 'customagent', ['name'], unique=False)
    op.create_index(op.f('ix_customagent_user_id'), 'customagent', ['user_id'], unique=False)
    
    # Create task_session table
    op.create_table(
        'tasksession',
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('thread_id', sa.String(), nullable=False),
        sa.Column('user_query', sa.String(), nullable=False),
        sa.Column('final_response', sa.String(), nullable=True),
        sa.Column('plan_summary', sa.String(), nullable=True),
        sa.Column('estimated_steps', sa.Integer(), nullable=True),
        sa.Column('execution_mode', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_tasksession_thread_id'), 'tasksession', ['thread_id'], unique=False)
    
    # Create subtask table
    op.create_table(
        'subtask',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('task_session_id', sa.String(), nullable=False),
        sa.Column('expert_type', sa.String(), nullable=False),
        sa.Column('task_description', sa.String(), nullable=True),
        sa.Column('output_result', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('execution_mode', sa.String(), nullable=True),
        sa.Column('depends_on', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['task_session_id'], ['tasksession.session_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtask_session_status'), 'subtask', ['task_session_id', 'status'], unique=False)
    op.create_index(op.f('ix_subtask_sort_order'), 'subtask', ['sort_order'], unique=False)
    op.create_index(op.f('ix_subtask_status'), 'subtask', ['status'], unique=False)
    
    # Create artifact table
    op.create_table(
        'artifact',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('sub_task_id', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['sub_task_id'], ['subtask.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_sub_task_id'), 'artifact', ['sub_task_id'], unique=False)
    op.create_index(op.f('ix_artifact_type'), 'artifact', ['type'], unique=False)
    
    # Create system_expert table
    op.create_table(
        'systemexpert',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('expert_key', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('system_prompt', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=False),
        sa.Column('is_dynamic', sa.Boolean(), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('expert_key')
    )
    op.create_index(op.f('ix_systemexpert_expert_key'), 'systemexpert', ['expert_key'], unique=True)
    
    # Create user_memories table (pgvector extension required)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table(
        'user_memories',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', sa.String(), nullable=True),  # Will use Vector type in real impl
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('memory_type', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    
    # Create mcp_servers table
    op.create_table(
        'mcp_servers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('sse_url', sa.String(), nullable=False),
        sa.Column('transport', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('icon', sa.String(), nullable=True),
        sa.Column('connection_status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sse_url')
    )
    op.create_index(op.f('ix_mcp_servers_is_active'), 'mcp_servers', ['is_active'], unique=False)
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_servers')
    op.drop_table('user_memories')
    op.drop_table('systemexpert')
    op.drop_table('artifact')
    op.drop_table('subtask')
    op.drop_table('tasksession')
    op.drop_table('customagent')
    op.drop_table('message')
    op.drop_table('thread')
    op.drop_table('user')
    # ### end Alembic commands ###
